[package]
name = "cargo-expand"
version = "1.0.27"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Wrapper around rustc -Zunpretty=expanded. Shows the result of macro expansion and #[derive] expansion."
repository = "https://github.com/dtolnay/cargo-expand"
documentation = "https://github.com/dtolnay/cargo-expand"
keywords = ["cargo", "subcommand", "expanded"]
categories = ["development-tools::cargo-plugins", "development-tools::debugging"]
edition = "2021"
readme = "README.md"
autotests = false

[dependencies]
atty = "0.2"
cargo-subcommand-metadata = { version = "0.1", optional = true }
clap = { version = "3.2.5", default-features = false, features = ["deprecated", "derive", "std", "suggestions"] }
prettyplease = { version = "0.1.13", optional = true, features = ["verbatim"] }
proc-macro2 = "1.0"
quote = { version = "1.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
syn-select = "0.2.1"
tempfile = "3.0"
termcolor = "1.0"
toml = "0.5"
toolchain_find = { version = "0.2", optional = true}

[dependencies.bat]
version = "0.21"
default-features = false
features = ["paging", "regex-fancy"]
optional = true

[dependencies.syn]
version = "1.0"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
members = ["tests"]

[features]
build-binary = ["cargo-subcommand-metadata", "bat", "toolchain_find"]

[[bin]]
name = "cargo-expand"
required-features = ["build-binary"]
